/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'usagi-rpg\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-key' : '&#xe00d;',
			'icon-hammer' : '&#xe00f;',
			'icon-fire' : '&#xe010;',
			'icon-spinner' : '&#xe016;',
			'icon-switch' : '&#xe026;',
			'icon-user' : '&#xe02a;',
			'icon-hammer-2' : '&#xe02b;',
			'icon-pause' : '&#xe02d;',
			'icon-warning' : '&#xe033;',
			'icon-notification' : '&#xe034;',
			'icon-play' : '&#xe035;',
			'icon-spam' : '&#xe036;',
			'icon-arrow-left' : '&#xe03a;',
			'icon-arrow-right' : '&#xe03f;',
			'icon-arrow-up-left' : '&#xe040;',
			'icon-arrow-up-right' : '&#xe041;',
			'icon-arrow-down-right' : '&#xe042;',
			'icon-warning-2' : '&#xe049;',
			'icon-help' : '&#xe04a;',
			'icon-x-altx-alt' : '&#xe04b;',
			'icon-check-alt' : '&#xe050;',
			'icon-arrow-down' : '&#xe051;',
			'icon-arrow-down-left' : '&#xe053;',
			'icon-arrow-up' : '&#xe054;',
			'icon-cc-by' : '&#xe05a;',
			'icon-pencil' : '&#xe05d;',
			'icon-cart' : '&#xe05f;',
			'icon-briefcase' : '&#xe060;',
			'icon-safari' : '&#xe066;',
			'icon-gift' : '&#xe067;',
			'icon-rss-alt' : '&#xe068;',
			'icon-movie' : '&#xe069;',
			'icon-bookmark' : '&#xe071;',
			'icon-exit' : '&#xe072;',
			'icon-star' : '&#xe073;',
			'icon-star-2' : '&#xe074;',
			'icon-remove' : '&#xe076;',
			'icon-bolt' : '&#xe07b;',
			'icon-IE' : '&#xe087;',
			'icon-firefox' : '&#xe088;',
			'icon-comment' : '&#xe08a;',
			'icon-earth' : '&#xe08d;',
			'icon-facebook' : '&#xe08e;',
			'icon-twitter' : '&#xe08f;',
			'icon-list' : '&#xe091;',
			'icon-flag' : '&#xe093;',
			'icon-chat' : '&#xe03d;',
			'icon-shield' : '&#xe045;',
			'icon-tv' : '&#xe046;',
			'icon-locked' : '&#xe048;',
			'icon-food' : '&#xe06b;',
			'icon-tv-2' : '&#xe07c;',
			'icon-camera' : '&#xe092;',
			'icon-film' : '&#xe095;',
			'icon-chronometer' : '&#xe096;',
			'icon-health' : '&#xe098;',
			'icon-cassette' : '&#xe099;',
			'icon-pacman' : '&#xe09a;',
			'icon-mute' : '&#xe09b;',
			'icon-basket' : '&#xe09c;',
			'icon-lab' : '&#xe09d;',
			'icon-bomb' : '&#xe09e;',
			'icon-lamp' : '&#xe0a0;',
			'icon-lamp-2' : '&#xe0a1;',
			'icon-magnifier' : '&#xe0a2;',
			'icon-patch' : '&#xe0a5;',
			'icon-chat-2' : '&#xe0a6;',
			'icon-chat-3' : '&#xe0a7;',
			'icon-stats' : '&#xe0a8;',
			'icon-hourglass' : '&#xe0aa;',
			'icon-profile' : '&#xe0a9;',
			'icon-envelope' : '&#xe0ab;',
			'icon-grid' : '&#xe0ac;',
			'icon-list-2' : '&#xe0ad;',
			'icon-lamp-3' : '&#xe0ae;',
			'icon-box' : '&#xe0af;',
			'icon-injection' : '&#xe0b1;',
			'icon-grid-2' : '&#xe0b2;',
			'icon-tools' : '&#xe0b3;',
			'icon-clipboard' : '&#xe0b4;',
			'icon-stop' : '&#xe0b5;',
			'icon-heart' : '&#xf004;',
			'icon-noun_project_12089' : '&#xe003;',
			'icon-noun_project_3888' : '&#xe012;',
			'icon-home' : '&#xf015;',
			'icon-drink' : '&#xe01a;',
			'icon-locked-2' : '&#xe01f;',
			'icon-unlocked' : '&#xe029;',
			'icon-umbrella' : '&#xf0e9;',
			'icon-screwdriver' : '&#xe052;',
			'icon-blocked' : '&#xe00b;',
			'icon-cancel' : '&#xe00c;',
			'icon-checkmark' : '&#xe055;',
			'icon-number' : '&#xe070;',
			'icon-number-2' : '&#xe080;',
			'icon-number-3' : '&#xe082;',
			'icon-number-4' : '&#xe084;',
			'icon-number-5' : '&#xe085;',
			'icon-number-6' : '&#xe086;',
			'icon-number-7' : '&#xe08b;',
			'icon-number-8' : '&#xe08c;',
			'icon-number-9' : '&#xe094;',
			'icon-number-10' : '&#xe0a4;',
			'icon-aid' : '&#xe00e;',
			'icon-dribbble' : '&#xe005;',
			'icon-pinterest' : '&#xe007;',
			'icon-music' : '&#xe009;',
			'icon-github' : '&#xe001;',
			'icon-google-plus' : '&#xe000;',
			'icon-deviantart' : '&#xe002;',
			'icon-bookmark-2' : '&#xe00a;',
			'icon-github-2' : '&#xe008;',
			'icon-bullhorn' : '&#xf0a1;',
			'icon-thumbs-up' : '&#xf087;',
			'icon-globe' : '&#xf0ac;',
			'icon-switch-2' : '&#xe006;',
			'icon-bookmark-3' : '&#xe011;',
			'icon-megaphone' : '&#xe014;',
			'icon-folder-open' : '&#xe004;',
			'icon-folder' : '&#xe0a3;',
			'icon-cabinet' : '&#xe013;',
			'icon-umbrella-2' : '&#xe015;',
			'icon-box-2' : '&#xe017;',
			'icon-notebook' : '&#xe018;',
			'icon-zoom-in' : '&#xe019;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};